name: Deploy test
on:
  push:
    branches: [ pixel ]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TEST_KEY }}
          known_hosts: 'none'

      - run: ssh-keyscan -H '173.230.133.198'  >> ~/.ssh/known_hosts
      - run: echo "${{ secrets.TEST_ENV }}" > .env
      - run: yarn install && yarn run build
      - run: rsync -azP ./build/  root@173.230.133.198:/var/www/bixel/ --delete